import { useEffect, useState } from "react";
import { contact, photos, projects, recommendations, work } from "./text/siteContent";

const asset = (path: string) => `${import.meta.env.BASE_URL}${path}`;
const graphPoint=(t:number)=>({
 x:110+(t-1)*170,
 y:650-((Math.pow(2,t)-2)/(Math.pow(2,5)-2))*530
});
const graphPath=(start:number,end:number,steps=72)=>Array.from({length:steps+1},(_,i)=>{
 const point=graphPoint(start+(end-start)*(i/steps));
 return `${i===0?"M":"L"}${point.x.toFixed(1)} ${point.y.toFixed(1)}`;
}).join(" ");
const futurePoint=graphPoint(5.18);
export default function Home(){
 const [menu,setMenu]=useState(false);const [active,setActive]=useState<number|null>(null);const [openRole,setOpenRole]=useState<number|null>(null);const [recIndex,setRecIndex]=useState(0);const [recPaused,setRecPaused]=useState(false);
 useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("in-view")),{threshold:.12});document.querySelectorAll(".reveal").forEach(e=>o.observe(e));return()=>o.disconnect()},[]);
 useEffect(()=>{const m=(e:MouseEvent)=>{document.documentElement.style.setProperty("--mx",`${e.clientX}px`);document.documentElement.style.setProperty("--my",`${e.clientY}px`)};addEventListener("mousemove",m);return()=>removeEventListener("mousemove",m)},[]);
 useEffect(()=>{if(recPaused)return;const timer=setInterval(()=>setRecIndex(i=>(i+1)%recommendations.length),6500);return()=>clearInterval(timer)},[recPaused]);
 const moveRecommendation=(direction:number)=>setRecIndex(i=>(i+direction+recommendations.length)%recommendations.length);
 const recommendation=recommendations[recIndex];
 const careerStages=[...work].reverse().map((job,i)=>({job,t:i+1,point:graphPoint(i+1)}));
 return <main><div className="cursor-glow"/>
  <nav className="nav"><a className="brand" href="#top">TD<span>.</span></a><div className={menu?"navlinks open":"navlinks"}>{["about","career","voices","projects","beyond","contact"].map(x=><a key={x} href={`#${x}`} onClick={()=>setMenu(false)}>{x}</a>)}</div><button className="menu" onClick={()=>setMenu(!menu)}>{menu?"Close":"Menu"}</button></nav>
  <section id="top" className="hero"><div className="hero-photo" style={{backgroundImage:`url(${asset("images/hero/tej-davuluri-portrait.jpg")})`}}/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">Data scientist · storyteller · explorer</p><h1>Tej<br/><em>Davuluri</em></h1><p className="intro">I find patterns in data, and stories everywhere else.</p></div><a className="scroll-cue" href="#about"><span>Scroll to explore</span><i>↓</i></a><div className="hero-index">01 / 06</div></section>
  <section id="about" className="story section-pad"><Label n="01">About</Label><div className="story-grid"><h2 className="reveal">Curiosity,<br/>in every <em>signal.</em></h2><div className="story-copy reveal"><p>I’m Sai Raghu Teja Davuluri, a San Francisco–based data scientist enthusiastic about predictive systems, generative AI and the decisions they can improve.</p><p>I enjoy the full journey from a messy business question to a useful model, a clear product and measurable impact. Accuracy matters, but only when it helps people make a better next move.</p><div className="story-links"><a href="https://github.com/Codewithtej" target="_blank">GitHub ↗</a><a href="https://www.linkedin.com/in/sai-raghu-teja-davuluri-93170a163/" target="_blank">LinkedIn ↗</a></div></div></div></section>
  <section id="career" className="career section-pad"><Label n="02">The journey</Label><div className="career-head reveal"><div><p className="career-kicker">Career journey · 2021, present</p><h2>A career in<br/><em>motion.</em></h2></div><p className="hover-prompt"><span>↘</span> Hover a company<br/>to explore the role</p></div><div className="career-plot reveal">
    <div className="plot-formula"><b>y</b><span>= 2<sup>t</sup></span></div>
    <span className="axis-y">Career growth</span><span className="axis-x">Time →</span>
    <svg className="curve-svg" viewBox="0 0 1000 720" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="careerLine" x1="0" y1="1" x2="1" y2="0"><stop offset="0" stopColor="#593a9e"/><stop offset="1" stopColor="#b59cff"/></linearGradient></defs><path className="observed-curve" d={graphPath(.4,5)}/><path className="future-curve" d={graphPath(5,5.18,18)}/></svg>
    {careerStages.map(({job:w,t,point},i)=><article key={w.company} className={`curve-node curve-node-${i} ${openRole===i?"is-open":""}`} style={{left:`${point.x/10}%`,top:`${point.y/7.2}%`}}><span className="math-label">t<sub>{t}</sub></span><button className="logo-point" data-company={w.company.toLowerCase()} aria-label={`Explore ${w.company} role at t${t}`} aria-expanded={openRole===i} onClick={()=>setOpenRole(openRole===i?null:i)}><img src={asset(w.logo)} alt=""/></button><div className="curve-popover"><div className="popover-head" data-company={w.company.toLowerCase()}><img src={asset(w.logo)} alt={`${w.company} logo`}/><div><small>{w.period} · t<sub>{t}</sub></small><h3>{w.company}</h3><span>{w.role}</span></div></div><p>{w.summary}</p><ul>{w.bullets.map(b=><li key={b}>{b}</li>)}</ul></div></article>)}
    <div className="future-node graph-future" style={{left:`${futurePoint.x/10}%`,top:`${futurePoint.y/7.2}%`}}><span>What’s next?</span><b>?</b></div>
  </div><p className="mobile-plot-hint">Tap each company point to expand the role.</p><div className="career-expertise reveal"><div className="career-expertise-head"><span>Selected expertise</span><code>capability_vector ∈ ℝ³</code></div><div className="career-expertise-grid"><article><span>01</span><h3>AI &amp; ML Engineering</h3><p>Predictive systems, generative AI, computer vision and deep learning.</p><small>LLMs · PyTorch · scikit-learn</small></article><article><span>02</span><h3>Forecasting &amp; Experimentation</h3><p>Time-series modeling, causal thinking and customer behavior.</p><small>Prophet · XGBoost · A/B testing</small></article><article><span>03</span><h3>Data Platforms &amp; Analytics</h3><p>Reliable data workflows and decision-ready analytical products.</p><small>Python · SQL · Fabric · Power BI</small></article></div></div><a className="resume reveal" href={asset("documents/tej-davuluri-resume.pdf")} target="_blank">View complete résumé <span>↗</span></a></section>
  <section id="voices" className="voices section-pad"><Label n="03">Recommendations</Label><div className="voices-head reveal"><h2>What collaborators <em>say.</em></h2><p>Managers, leaders and mentors on the way I work.</p></div><div className="recommendation-band reveal" onMouseEnter={()=>setRecPaused(true)} onMouseLeave={()=>setRecPaused(false)} onFocusCapture={()=>setRecPaused(true)} onBlurCapture={()=>setRecPaused(false)}><span className="quote-mark" aria-hidden="true">“</span><button className="rec-arrow rec-prev" onClick={()=>moveRecommendation(-1)} aria-label="Previous recommendation">←</button><div className={`recommendation-slide ${recommendation.quote.length>360?"is-long":""}`} key={`${recommendation.name}-${recIndex}`} aria-live="polite"><blockquote>“{recommendation.quote}”</blockquote><div className="recommender"><span className="rec-rule"/><strong>{recommendation.name}</strong><small>{recommendation.role}</small></div></div><button className="rec-arrow rec-next" onClick={()=>moveRecommendation(1)} aria-label="Next recommendation">→</button><div className="rec-dots" aria-label="Choose recommendation">{recommendations.map((r,i)=><button key={r.name} className={i===recIndex?"active":""} onClick={()=>setRecIndex(i)} aria-label={`Show recommendation ${i+1}`} aria-current={i===recIndex?"true":undefined}/>)}</div><span className="rec-count">{String(recIndex+1).padStart(2,"0")} / {String(recommendations.length).padStart(2,"0")}</span></div></section>
  <section id="projects" className="projects section-pad"><Label n="04">Selected projects</Label><div className="projects-head reveal"><h2>Things I’ve<br/><em>built.</em></h2><div><p>Open-source experiments across agents, retrieval, vision, forecasting and machine-learning foundations.</p><code>github.com/Codewithtej</code></div></div><div className="project-grid">{projects.map((p,i)=><a className="project-card reveal" href={p.href} target="_blank" rel="noreferrer" key={p.repo}><span className="project-number">P{String(i+1).padStart(2,"0")}</span><span className="repo-name"><i>●</i> Codewithtej / {p.repo}</span><h3>{p.name}</h3><p>{p.description}</p><div className="project-stack">{p.stack.map(s=><span key={s}>{s}</span>)}</div><span className="repo-arrow">View repository ↗</span></a>)}</div><a className="all-projects reveal" href="https://github.com/Codewithtej?tab=repositories" target="_blank" rel="noreferrer">Explore all 24 repositories <span>↗</span></a></section>
  <section id="beyond" className="beyond section-pad"><Label n="05">Beyond work</Label><div className="beyond-intro"><h2 className="reveal">Beyond the<br/><em>models &amp; data.</em></h2><div className="reveal"><p>The résumé is one useful dataset. The rest has rover dust, finish lines, a crowded camera roll and a few Python lessons delivered to a very honest audience.</p><code>person &gt; profession</code></div></div><article className="rover-story reveal"><div className="rover-image"><img src={asset("images/personal/mars-rover-manipal-team.png")} alt="Mars Rover Manipal team with their rover at the 2019 University Rover Challenge"/><span>Utah · 2019</span></div><div className="rover-copy"><span>Before the models</span><h3>We built for <em>Mars.</em></h3><p>At Manipal, I was part of Mars Rover Manipal, a team that turned sketches, electronics and stubborn optimism into a working rover. At the 2019 University Rover Challenge, we finished <strong>8th globally</strong> and <strong>1st in Asia</strong> among 84 teams, and won the Barainca Award for the best Science team.</p><p>It left me with a lesson I still use in AI: ambitious systems work when curious people from different disciplines solve the hard parts together.</p><div><b>#08 Global</b><b>#01 Asia</b><b>Best Science Team</b></div></div></article><div className="hobby-heading reveal"><span>Three scenes, no résumé bullets</span><p>The parts of me that make the work, and the person doing it, more interesting.</p></div><div className="personal-stories reveal"><article className="personal-card lens-card"><div className="canvas-grid">{photos.map((p,i)=><button key={p[0]} onClick={()=>setActive(i)} aria-label={`Open ${p[1]}`}><img src={asset(p[0])} alt={p[1]}/></button>)}</div><div className="personal-copy"><span>01 · My Canvas · 23 frames</span><h3>Collecting better pixels.</h3><p>Every photograph from My Canvas, city lines, quiet landscapes and the occasional frame that survives my ruthless camera-roll cleanup.</p></div></article><article className="personal-card"><img src={asset("images/personal/mangalore-10k-finish.jpg")} alt="Tej after completing the Mangalore 10K"/><div className="personal-copy"><span>02 · Running</span><h3>10K, completed.</h3><p>Mangalore Marathon, 2022. The smile says “worth it.” My legs had a more nuanced review.</p></div></article><article className="personal-card"><img src={asset("images/personal/teach-code-for-good.jpg")} alt="Tej mentoring students through Teach Code for Good"/><div className="personal-copy"><span>03 · Mentoring</span><h3>Code, then confidence.</h3><p>Teaching Python, SQL and HTML through Teach Code for Good, where the questions are direct and the progress is genuinely joyful.</p></div></article></div></section>
  <footer id="contact" className="footer section-pad"><Label n="06">For recruiters</Label><div className="recruiter-head reveal"><p>Building an AI or data team?</p><h2>Let’s discuss where I can create <em>impact.</em></h2></div><div className="recruiter-contact reveal"><a href={contact.linkedin} target="_blank" rel="noreferrer"><span>LinkedIn</span><b>Connect professionally</b><i>↗</i></a><a href={`mailto:${contact.email}`}><span>Email</span><b>{contact.email}</b><i>↗</i></a><a href={`tel:${contact.phoneHref}`}><span>Call</span><b>{contact.phoneDisplay}</b><i>↗</i></a></div><div className="footer-bottom"><span>© 2026 Tej Davuluri</span><span>San Francisco, CA</span><a href="#top">Back to top ↑</a></div></footer>
  {active!==null&&<div className="lightbox" role="dialog" onClick={()=>setActive(null)}><button>Close ×</button><img src={asset(photos[active][0])} alt={photos[active][1]}/><div><b>{photos[active][1]}</b><span>{photos[active][2]}</span></div></div>}
 </main>
}
function Label({n,children}:{n:string,children:React.ReactNode}){return <div className="section-label reveal"><span>{n}</span>{children}</div>}
